AllCops:
  Exclude:
    - tmp/**/*

Documentation:
  Enabled: false

# Style/RegexpLiteral:
#   Enabled: false

Metrics/MethodLength:
  Max: 23

Metrics/ClassLength:
  Max: 256

Metrics/AbcSize:
  Enabled: false
